name: Run Recipe Bot

on:
  schedule:
    - cron: '0 8,18 * * *'  # Запуск в 8:00 и 18:00 по UTC
  workflow_dispatch:  # Позволяет запускать workflow вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: python bot.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}
          IMAGE_API_URL: ${{ secrets.IMAGE_API_URL }}
          IMAGE_API_KEY: ${{ secrets.IMAGE_API_KEY }}
